import { For, Show, createSignal } from "solid-js";
import type { RoutePath } from "../types";
import type { AppData } from "../data/types";
import { Button, Card, IconBadge } from "../components/ui";
import { createConvexAction, createMutation } from "../convex";
import { api } from "../data/live";

export function StudyScreen(props: { navigate: (path: RoutePath) => void; data: AppData["study"] }) {
  const [question, setQuestion] = createSignal("");
  const [answer, setAnswer] = createSignal("");
  const [thinking, setThinking] = createSignal(false);
  const [listening, setListening] = createSignal(false);
  const [shareNotice, setShareNotice] = createSignal("");
  const explain = createConvexAction(api.assistant.explain);
  const saveMessage = createMutation(api.assistant.saveMessage);

  const ask = async (prompt = question()) => {
    const study = props.data;
    if (!study || !prompt.trim()) return;
    setQuestion(prompt);
    setThinking(true);
    try {
      await saveMessage({ explanationId: study._id, topic: study.topic, role: "user", content: prompt });
      const result = await explain({ topic: study.topic, question: prompt, context: `${study.grade} ${study.subject}: ${study.introBody}` });
      await saveMessage({ explanationId: study._id, topic: study.topic, role: "assistant", content: result.answer });
    } catch (error) {
      setAnswer(error instanceof Error ? error.message : "I could not answer that right now.");
    } finally { setThinking(false); }
  };

  const listen = () => {
    const study = props.data;
    if (!study || !("speechSynthesis" in window)) { setShareNotice("Text-to-speech is not available in this browser."); return; }
    if (listening()) { window.speechSynthesis.cancel(); setListening(false); return; }
    const speech = new SpeechSynthesisUtterance(`${study.introBody}. ${study.steps.map((step) => `${step.title}. ${step.body}`).join(" ")}`);
    speech.rate = .95;
    speech.onend = () => setListening(false);
    speech.onerror = () => setListening(false);
    setListening(true);
    window.speechSynthesis.speak(speech);
  };

  const share = async () => {
    const study = props.data;
    if (!study) return;
    const text = `${study.topic}\n\n${study.introBody}\n\n${study.formula}`;
    try {
      if (navigator.share) await navigator.share({ title: `${study.topic} · Quizzly`, text });
      else { await navigator.clipboard.writeText(text); setShareNotice("Explanation copied to your clipboard."); }
    } catch { setShareNotice("Sharing was cancelled."); }
  };

  return (
    <Show when={props.data} fallback={<Card><h2>No explanation is ready yet</h2><p>Upload a note first and Quizzly will build your study material.</p><Button onClick={() => props.navigate("/notes")}>Upload notes</Button></Card>}>
      {(study) => <div class="page-stack">
        <header class="study-toolbar"><Button variant="ghost" onClick={() => props.navigate("/notes")}>← Back to notes</Button><div class="document-picker"><IconBadge icon="▤" size="sm" />{study().topic} — {study().grade} {study().subject}</div><Button variant="ghost" onClick={() => props.navigate("/performance")}>View progress</Button></header>
        <div class="content-with-rail">
          <div class="main-column">
            <Card>
              <div class="section-heading"><div class="flex items-center gap-3"><IconBadge icon="✦" size="lg" /><div><h1 class="section-title">{study().title}</h1><p>Generated by {study().generatedBy}</p></div></div><div class="flex gap-2"><Button variant="secondary" onClick={listen}>{listening() ? "■ Stop" : "◖ Listen"}</Button><Button variant="secondary" onClick={() => void share()}>↗ Share</Button></div></div>
              <Show when={shareNotice()}><div class="inline-notice"><span>i</span><p>{shareNotice()}</p><button onClick={() => setShareNotice("")} aria-label="Dismiss">×</button></div></Show>
              <div class="explanation-hero"><div><span class="bot-face">••</span></div><div><strong>{study().introTitle}</strong><p>{study().introBody}</p></div><div class="plant-visual" aria-label={`${study().topic} illustration`}><span class="sun">☀</span><span class="leaf">♧</span><span class="plant-pot">▰</span><small>{study().formula}</small></div></div>
              <div class="study-steps"><h2>How it works</h2><For each={study().steps}>{(step) => <article><span class="step-number">{step.order}</span><IconBadge icon={step.icon} tone={step.tone} /><div><strong>{step.title}</strong><p>{step.body}</p></div></article>}</For></div>
              <div class="formula-callout"><IconBadge icon="⌁" tone="green" /><strong>In short:</strong><span>{study().formula}</span></div>
            </Card>
            <Card class="quiz-cta"><div><h2>Want to practice this topic?</h2><p>Use the quiz generated from this explanation.</p></div><Button onClick={() => props.navigate("/quiz")}>✦ Start quiz</Button></Card>
          </div>
          <aside class="right-rail">
            <Card><div class="section-heading compact"><div><h2>Key points</h2><p>Save these for quick recall</p></div></div><ul class="key-list"><For each={study().keyPoints}>{(point) => <li><span>✓</span>{point.text}</li>}</For></ul></Card>
            <Card><div class="section-heading compact"><div><h2>Related topics</h2><p>Explore the connection with AI</p></div></div><div class="related-list"><For each={study().relatedTopics}>{(topic) => <button onClick={() => void ask(`How is ${topic.title} connected to ${study().topic}?`)}>{topic.title}<span>→</span></button>}</For></div></Card>
            <Card class="ask-card"><div class="section-heading compact"><div><h2>Ask your AI buddy</h2><p>Your conversation is saved to Convex.</p></div></div><Show when={study().messages.length > 0}><div class="conversation-list"><For each={study().messages}>{(message) => <div class={message.role}><small>{message.role === "assistant" ? "Quizzly" : "You"}</small><p>{message.content}</p></div>}</For></div></Show><div class="prompt-list"><For each={study().prompts}>{(prompt) => <button onClick={() => void ask(prompt.text)}>{prompt.text}<span>→</span></button>}</For></div><Show when={answer() || thinking()}><div class="ai-answer"><span>✦</span><p>{thinking() ? "Thinking through your notes…" : answer()}</p></div></Show><form class="ask-input" onSubmit={(event) => { event.preventDefault(); void ask(); }}><input value={question()} onInput={(event) => setQuestion(event.currentTarget.value)} placeholder={`Ask about ${study().topic}…`} aria-label="Ask AI" /><button type="submit" disabled={thinking()} aria-label="Send question">➤</button></form></Card>
          </aside>
        </div>
      </div>}
    </Show>
  );
}
